# Generated by Django 4.2.24 on 2025-09-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '00001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='phone ',
            new_name='phone',
        ),
    ]
