# Generated by Django 4.2.24 on 2025-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_phone__record_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
