# Generated by Django 4.2.24 on 2025-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
